SS Hull
friends-library/henry-hull pull request #7
Opened 2019-03-20 04:34 UTC by maijapapaya

@jaredh159 @Henderjay

2019-03-20 04:37 UTC, maijapapaya commented
This one was a little more tricky than some of the others. I'm sorry if there's a lot to fix. I also realized I like when there's two editions to work on because I catch more things I missed.

2019-03-21 13:24 UTC, jaredh159 requested changes
Nice job on some tricky stuff here.  Left a few comments for changes, mostly because I decided to add another _type_ of `minute` after reviewing this. Let me know if you have any questions!

2019-03-21 13:24 UTC, jaredh159 commented on journal/modernized/2-journal.adoc
> +[.embedded-content-document.letter]
Hmmm... I think we should add another _type_ -- it will be pretty rare, but useful I think.  Let's change this to `.minute`.

2019-03-21 13:24 UTC, jaredh159 commented on journal/modernized/2-journal.adoc
> +//maybe this should be an epistle?
Yeah, it's close, but I think we should change it to epistle. Even though he uses the word "address" it's definitely to Friends, which is why I think you left this comment. Good catch, let's make the change.

2019-03-21 13:24 UTC, jaredh159 commented on journal/modernized/2-journal.adoc
> +//not sure if this above should be embedded^^
Ok, yeah, confusing.  I thought it was one thing, but then I read it again, and now I think we probably should embed it on it's own.  Not sure what _type_ to give it though... Let's leave it blank for now, just `[.embedded-content-document]`

2019-03-21 13:24 UTC, jaredh159 commented on journal/modernized/2-journal.adoc
> +//^^ Not sure how "minute" should be labeled. I think there was another one above, and I can't remember if I made a note about it or not. Should it be embedded? I think I embedded the other one.
Ok, so I think we should embed this section, and use the new type `.minute`.  Start the embed right before the sentence that starts "Soon after this meeting directed the reprinting "

2019-03-21 13:24 UTC, jaredh159 commented on journal/original/2-journal.adoc
> +[.embedded-content-document.letter]
also change to `.minute`

2019-03-21 13:24 UTC, jaredh159 commented on journal/original/2-journal.adoc
> +[.embedded-content-document.address]
also switch to `epistle`

2019-03-21 13:24 UTC, jaredh159 commented on journal/original/2-journal.adoc
>  [.signed-section-context-close]
The section above here, treat the same was as I commented in the modernized, embedding it without a type.

2019-03-21 13:24 UTC, jaredh159 commented on journal/original/2-journal.adoc
>  the Meeting for Sufferings of that Yearly Meeting directed an
Same here as with modernized, wrap an embedded "minute" around the chunk below, starting just before "Soon after this meeting directed the reprinting"

2019-03-22 15:56 UTC, merged

2019-03-22 15:56 UTC, jaredh159 commented
Nice, merged. :)